# Generated by Django 6.0 on 2025-12-30 00:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='receipt',
            field=models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='تصویر رسید'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='تاریخ پرداخت'),
        ),
    ]
