# Generated by Django 6.0 on 2025-12-30 02:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نظرسنجی')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='لینک یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='استاد')),
            ],
            options={
                'verbose_name': 'نظرسنجی استاد',
                'verbose_name_plural': 'نظرسنجی\u200cهای اساتید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500, verbose_name='متن سوال')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='surveys.teachersurvey', verbose_name='نظرسنجی')),
            ],
            options={
                'verbose_name': 'سوال نظرسنجی استاد',
                'verbose_name_plural': 'سوالات نظرسنجی استاد',
            },
        ),
        migrations.CreateModel(
            name='TeacherSurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آدرس IP')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='surveys.teachersurvey', verbose_name='نظرسنجی')),
            ],
            options={
                'verbose_name': 'پاسخ\u200cنامه نظرسنجی استاد',
                'verbose_name_plural': 'پاسخ\u200cنامه\u200cهای نظرسنجی استاد',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeacherSurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(choices=[(1, 'خیلی بد'), (2, 'بد'), (3, 'متوسط'), (4, 'خوب'), (5, 'خیلی خوب')], verbose_name='امتیاز')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.teachersurveyquestion', verbose_name='سوال')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='surveys.teachersurveyresponse', verbose_name='پاسخ\u200cنامه')),
            ],
            options={
                'verbose_name': 'پاسخ نظرسنجی استاد',
                'verbose_name_plural': 'پاسخ\u200cهای نظرسنجی استاد',
            },
        ),
    ]
