# Generated by Django 6.0 on 2025-12-30 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='days',
            field=models.CharField(blank=True, max_length=100, verbose_name='روزهای برگزاری'),
        ),
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.CharField(blank=True, max_length=100, verbose_name='ساعت برگزاری'),
        ),
    ]
