# Generated by Django 6.0 on 2025-12-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Key for frontend reference (e.g., home_hero_title)', max_length=100, unique=True)),
                ('value', models.TextField(blank=True, help_text='Text content', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image content (optional)', null=True, upload_to='site_images/')),
                ('description', models.CharField(blank=True, help_text='Description for admin to understand what this setting does', max_length=255)),
            ],
        ),
    ]
